import React from "react";

export const Cart = () => {
	//USAR CONTEXT CARTCONTEXT
	//DESESTRUCTURAR EL CARRITO
	// HACER UN MAP DEL CARRITO PARA MOSTRAR TODOS LOS PRODUCTO QUE HAY

	//DESESUTRUCURAR PRECIOTOTAL Y MOSTRARLO

	//DESESTRUCTURAR eliminarProducto y agregarlo como evento al Boton Eliminar

	//SI NO HAY PRODUCTOS MOSTRAR UN MENSAJE Y POSIBILIDAD DE NAVEGAR AL HOME

	return <div>LISTA DE PRODUCTOS EN MI CARRITO</div>;
};
